apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    name: multi-port-app # Ensure this matches the label on your Pods
  type: NodePort # This should be under `spec`
  ports:
  - protocol: TCP
    name: port80
    port: 80
    targetPort: 80
    nodePort: 30001
  - protocol: TCP
    name: port443
    port: 443
    targetPort: 443
    nodePort: 30002
