apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600'] # Keep the container running
    volumeMounts:
    - mountPath: /data # Directory inside the Pod
      name: mydir
  volumes:
  - name: mydir
    hostPath:
      path: /data/host-directory # Path on the host
      type: DirectoryOrCreate
