apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: app-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-data" # Mounting the secret as a volume
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret

