apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from the PVC' > /mnt/testfile && sleep 3600"]
    volumeMounts:
    - name: pvc-storage
      mountPath: /mnt
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: dynamic-pvc
