apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/manual-pv
  storageClassName: ebs-storage-class
  accessModes:
  - ReadWriteOnce

