apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-resizable
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Replace with your StorageClass if different
